'use server'

import { GoogleGenAI } from '@google/genai'
import { createServerClient } from '@/lib/supabase'

// Must match the filter in RouteDetailModal — if a description contains any of these,
// it was generated by an old prompt and should be overwritten with fresh AI text.
const BAD_PHRASES = ['融合', '人文風情', '自然生態', '值得一遊', '不容錯過'];
function isStaleDescription(text: string | null | undefined): boolean {
  if (!text) return true;
  return BAD_PHRASES.some(p => text.includes(p));
}

export async function generateHighlightFallback(name: string): Promise<string> {
  if (!name.trim()) return ''

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! })

  let text = ''
  try {
    const result = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite',
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `你是一位台東文化觀察家，以詩意卻不矯情的散文語氣介紹台東各地。
請為「${name}」寫一段不超過 40 字的精煉短介。
規則：
- 禁止使用「融合」「人文風情」「自然生態」「值得一遊」「不容錯過」等陳腐詞彙
- 語感如旅遊散文或詩句，充滿畫面感
- 不加任何 Markdown 格式或換行
- 只輸出介紹文字本身，不加引號或說明`,
            },
          ],
        },
      ],
    })
    text = (result.candidates?.[0]?.content?.parts?.[0]?.text ?? '').trim()
  } catch (err) {
    console.warn('[generateHighlightFallback] Gemini 呼叫失敗:', err)
    return ''
  }

  if (!text) return ''

  // 寫回 Supabase（places 優先，再試 foods）
  // 注意：Supabase JS 的 .update() 不拋出例外，錯誤只在 { error } 欄位，必須明確檢查。
  try {
    const sb = createServerClient()

    // ── 1. 嘗試 places 表 ──────────────────────────────────────────────────
    const { data: place, error: placeSelectErr } = await sb
      .from('places')
      .select('id, description')
      .eq('name', name)
      .maybeSingle()

    if (placeSelectErr) {
      console.warn('[generateHighlightFallback] places SELECT 失敗:', placeSelectErr.message)
    } else if (place) {
      if (isStaleDescription(place.description)) {
        const { error: placeUpdateErr } = await sb
          .from('places')
          .update({ description: text })
          .eq('id', place.id)

        if (placeUpdateErr) {
          console.warn('[generateHighlightFallback] places UPDATE 失敗:', placeUpdateErr.message,
            '— 若為 RLS 錯誤，請確認 wildTaitung 環境已設定 SUPABASE_SERVICE_KEY')
        }
      }
      // 無論 places 是否更新成功，找到匹配就不再查 foods
      return text
    }

    // ── 2. 嘗試 foods 表 ───────────────────────────────────────────────────
    const { data: food, error: foodSelectErr } = await sb
      .from('foods')
      .select('id, description')
      .eq('name', name)
      .maybeSingle()

    if (foodSelectErr) {
      console.warn('[generateHighlightFallback] foods SELECT 失敗:', foodSelectErr.message)
    } else if (food) {
      if (isStaleDescription(food.description)) {
        const { error: foodUpdateErr } = await sb
          .from('foods')
          .update({ description: text })
          .eq('id', food.id)

        if (foodUpdateErr) {
          console.warn('[generateHighlightFallback] foods UPDATE 失敗:', foodUpdateErr.message,
            '— 若為 RLS 錯誤，請確認 wildTaitung 環境已設定 SUPABASE_SERVICE_KEY')
        }
      }
    } else {
      // places 與 foods 均無此名稱的記錄（亮點為活動描述而非景點名稱）
      console.warn('[generateHighlightFallback] 找不到對應記錄，無法快取描述:', name)
    }
  } catch (err) {
    console.warn('[generateHighlightFallback] 快取寫回發生例外:', err)
  }

  return text
}
